baseURL = "https://lucyw.netlify.app"
languageCode = "en-us"
paginate = 4
summaryLength = "10"
theme = "thomson-hugo"
title = "Thomson-Minimal Hugo Portfolio Temaplate"
[[menu.main]]
name = "Contact"
url = "contact"
weight = 4
[[menu.main]]
name = "Portfolio"
url = "portfolio"
weight = 3
[[menu.main]]
name = "About"
url = "about"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
address = "Raleigh, North Carolina, USA"
author = "themefisher"
contact_form_action = "#"
copyright = "Copyrighht &copy; 2020 a theme by [themefisher](https://themefisher.com)"
description = "This is meta description"
email = "lucywarren0@email.com"
google_analitycs_id = ""
home = "Home"
logo = "images/logo.png"
mobile = "(919)665-9946"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify/css/themify-icons.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.carousel.min.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.theme.default.min.css"
[[params.plugins.css]]
link = "plugins/animated-text/animated-text.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/owl-carousel/owl.carousel.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/animated-text/animated-text.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-instagram"
link = "#"
[[params.social]]
icon = "ti-dribbble"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
