# default configuration
baseURL = "https://lucyw.netlify.app"
languageCode = "en-us"
theme = "thomson-hugo"
title = "Thomson-Minimal Hugo Portfolio Temaplate"
summaryLength = "10"
paginate = 4

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify/css/themify-icons.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.carousel.min.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.theme.default.min.css"
[[params.plugins.css]]
link = "plugins/animated-text/animated-text.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/owl-carousel/owl.carousel.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/animated-text/animated-text.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"


# menu
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "about"
weight = 2

[[menu.main]]
name = "Portfolio"
url = "portfolio"
weight = 3

[[menu.main]]
name = "Contact"
url = "contact"
weight = 4

[[menu.main]]
name = "Blog"
url = "blog"
weight = 5

[[menu.main]]
name = "Dropdown"
url = "#"
weight = 6

  [[menu.main]]
  parent = "Dropdown"
  name = "Child 1"
  url = "#"
  weight = 1

  [[menu.main]]
  parent = "Dropdown"
  name = "Child 2"
  url = "#"
  weight = 2



# default parameters
[params]
home = "Home"
logo = "images/logo.png"
# contact info
mobile = "(919)665-9946"
email = "lucywarren0@email.com"
address = "Raleigh, North Carolina, USA"
# meta description
author = "themefisher"
description = "This is meta description"
# google analitycs
google_analitycs_id = ""
# contact form action 
contact_form_action = "#" # contact form works with : https://formspree.io
# copyright
copyright = "Copyrighht &copy; 2020 a theme by [themefisher](https://themefisher.com)"

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# google map
#[params.gmap]
#enable = true
#gmap_api = "https://www.google.co.uk/maps/place/Diagon+Alley/@51.693249,-0.4196331,3a,75y,274.23h,91.66t/data=!3m6!1e1!3m4!1su1gcE6cVKELE_xgImwtVHQ!2e0!7i13312!8i6656!4m5!3m4!1s0x0:0x8fb53b8c2955148d!8m2!3d51.6907366!4d-0.4173784?hl=en"
#map_latitude = "51.693249"
#map_longitude = "-0.4196331"
#map_marker = "images/marker.png"

# social site
[[params.social]]
icon = "ti-facebook"
link = "#"

[[params.social]]
icon = "ti-instagram"
link = "#"

[[params.social]]
icon = "ti-dribbble"
link = "#"

[[params.social]]
icon = "ti-twitter-alt"
link = "#"
